# Generated by Django 5.0 on 2023-12-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_relationtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=50)),
            ],
        ),
    ]
