# Generated by Django 5.0 on 2023-12-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_scholarshiptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_electionposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_position', models.CharField(max_length=50)),
            ],
        ),
    ]
