# Generated by Django 5.0 on 2023-12-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_electionposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_financehead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financehead_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fdate', models.DateField()),
                ('sdate', models.DateField()),
            ],
        ),
    ]
