# Generated by Django 5.0 on 2024-01-05 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_financehead'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_scholarshipname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=50)),
                ('scholarship_details', models.CharField(max_length=50)),
                ('proof_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_proof')),
                ('scholarship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_scholarshiptype')),
            ],
        ),
    ]
