# Generated by Django 5.0 on 2024-01-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_scholarshipname'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_electiondeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('nodate', models.DateField()),
                ('vedate', models.DateField()),
                ('eldate', models.DateField()),
                ('redate', models.DateField()),
                ('podate', models.DateField()),
            ],
        ),
    ]
