# Generated by Django 5.0 on 2024-01-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_electiondeclaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_electiondeclaration',
            name='podate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
