# Generated by Django 5.0 on 2024-01-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_relatives',
        ),
    ]
