# Generated by Django 5.0 on 2024-01-26 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0013_alter_tbl_electiondeclaration_podate'),
        ('Guest', '0003_initial'),
        ('Member', '0002_delete_tbl_relatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_relatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='MemberDocs/')),
                ('address', models.TextField()),
                ('refer_id', models.IntegerField()),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_memberadding')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_relationtype')),
            ],
        ),
    ]
