# Generated by Django 5.0 on 2024-01-27 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_tbl_electiondeclaration_podate'),
        ('Guest', '0003_initial'),
        ('Member', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_scholarshipapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('document', models.FileField(upload_to='MemberDocs/')),
                ('date', models.DateField()),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_memberadding')),
                ('relative_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.tbl_relatives')),
                ('scholarship_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_scholarshipname')),
            ],
        ),
    ]
