# Generated by Django 5.0 on 2024-01-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_tbl_scholarshipapply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_scholarshipapply',
        ),
    ]
