# Generated by Django 5.0 on 2024-01-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0006_tbl_scholarshipapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_scholarshipapply',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
