# Generated by Django 5.0 on 2024-01-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0007_alter_tbl_scholarshipapply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_scholarshipapply',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
