# Generated by Django 5.0 on 2024-01-28 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_tbl_electiondeclaration_podate'),
        ('Guest', '0003_initial'),
        ('Member', '0009_tbl_chittyjoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_loanapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('document', models.FileField(upload_to='MemberDocs/')),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('loan_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_loan')),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_memberadding')),
                ('proof_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_proof')),
            ],
        ),
    ]
