# Generated by Django 5.0 on 2024-01-28 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceHead', '0002_tbl_addloanname'),
        ('Member', '0010_tbl_loanapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_loanapply',
            name='loan_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceHead.tbl_addloanname'),
        ),
    ]
