# Generated by Django 5.0 on 2024-02-10 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_tbl_electiondeclaration_podate'),
        ('Guest', '0003_initial'),
        ('Member', '0011_alter_tbl_loanapply_loan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_electionapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('election_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_electiondeclaration')),
                ('election_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_electionposition')),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_memberadding')),
            ],
        ),
    ]
