# Generated by Django 5.0 on 2024-02-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
        ('Member', '0012_tbl_electionapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electionapply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.tbl_electionapply')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_memberadding')),
                ('relative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Member.tbl_relatives')),
            ],
        ),
    ]
