# Generated by Django 5.0 on 2024-03-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0016_delete_tbl_weeklycollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_monthlycollection',
        ),
    ]
