# Generated by Django 5.0 on 2024-03-01 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceHead', '0004_tbl_weeklycollection'),
        ('Guest', '0003_initial'),
        ('Member', '0017_delete_tbl_monthlycollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_monthlycollectionpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_memberadding')),
                ('monthlycollection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceHead.tbl_monthlycollection')),
            ],
        ),
    ]
