# Generated by Django 5.0 on 2024-03-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
        ('Member', '0021_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_repaymentloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_date', models.DateField(auto_now_add=True)),
                ('loanapply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.tbl_loanapply')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_memberadding')),
            ],
        ),
    ]
