# Generated by Django 5.0 on 2024-03-02 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_events'),
        ('FinanceHead', '0006_tbl_loancalender'),
        ('Guest', '0003_initial'),
        ('Member', '0022_tbl_repaymentloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chittyfunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='Doc/')),
                ('status', models.IntegerField(default=0)),
                ('chitty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceHead.tbl_chitty')),
                ('member_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_memberadding')),
                ('proof_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_proof')),
                ('relative_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Member.tbl_relatives')),
            ],
        ),
    ]
