# Generated by Django 5.0 on 2024-01-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0010_tbl_financehead'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chitty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chitty_name', models.CharField(max_length=50)),
                ('chitty_details', models.CharField(max_length=50)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_financehead')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_scheme')),
            ],
        ),
    ]
