# Generated by Django 5.0 on 2024-03-01 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_tbl_electiondeclaration_podate'),
        ('FinanceHead', '0004_tbl_weeklycollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chittycalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('no_installment', models.IntegerField()),
                ('chitty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceHead.tbl_chitty')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_financehead')),
            ],
        ),
    ]
