# Generated by Django 5.0 on 2024-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceHead', '0006_tbl_loancalender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_chittycalender',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_chittycalender',
            name='enddate',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_chittycalender',
            name='no_installment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_chittycalender',
            name='startdate',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_loancalender',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_loancalender',
            name='enddate',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_loancalender',
            name='no_installment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_loancalender',
            name='startdate',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_monthlycollection',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_weeklycollection',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
