# Generated by Django 5.0 on 2023-12-30 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0010_tbl_financehead'),
        ('Guest', '0002_delete_tbl_memberadding'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_memberadding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='MemberDocs/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location')),
            ],
        ),
    ]
